runejs/refactored-client-435

.gitignore, README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, settings.gradle
This pull request adds support for Gradle as a build system instead of Maven.
The main entrypoint into Gradle is via the `gradlew` shell script, or the `gradlew.bat` script for Windows. The script will detect the gradle version as supplied by the configuration in the `gradle/wrapper` directory.
**Note:** These scripts have been generated by gradle itself via `gradle init`.
The interesting files here will mainly be centered around `build.gradle` and `settings.gradle`, which configure Gradle specifically for this project.
I have also included a subsection in the README under "Usage" that covers the two most common scenarios.
Using Gradle generates files in the `build` directory, and caches gradle-specific data and executables in the `.gradle` directory. These have been ignored.
=> add gradle wrapper

src/main/java/com/jagex/runescape/cache/media/TypeFace.java
add a case for `<str>` tag without a color attribute
didnt add the # check we added @Promises , I think that needs a bit more thinking with the substring
=> add a case for default strikethrough

src/main/java/com/jagex/runescape/cache/media/gameInterface/GameInterface.java
revert the client-sided cutscene block, because we can use player.busy on the server for this
=> revert cutscene block

src/main/java/org/runejs/Configuration.java
When using a configuration file from before SERVER_DISPLAY_NAME was a variable, the client will crash when attempting to open the console. This patch provides compatibility for this scenario.
=> Prevent crash when using older configuration file

src/main/java/org/runejs/client/cache/def/UnderlayDefinition.java
The green and blue variable was around the wrong way.
```java
public void calculateHsl() {
double r = (double) (color >> 16 & 0xff) / 256.0;
double b = (double) (color & 0xff) / 256.0;
double g = 1.0;//(double) ((color & 0xff68) >> 8) / 256.0;
```
When setting green to 1.0 (maximum) 
I can see green is now correctly set to `g` and not `b`
=> Correct variable for green and blue in calculateHsl() in UnderlayDefinition.java

src/main/java/org/runejs/client/Class40_Sub5_Sub17_Sub6.java, src/main/java/org/runejs/client/Class43.java, src/main/java/org/runejs/client/Class51.java, src/main/java/org/runejs/client/Class60.java, src/main/java/org/runejs/client/Landscape.java, src/main/java/org/runejs/client/LinkedList.java, src/main/java/org/runejs/client/Main.java, src/main/java/org/runejs/client/MovedStatics.java, src/main/java/org/runejs/client/RSCanvas.java, src/main/java/org/runejs/client/cache/def/GameObjectDefinition.java, src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java, src/main/java/org/runejs/client/input/KeyFocusListener.java, src/main/java/org/runejs/client/media/renderable/actor/Actor.java, src/main/java/org/runejs/client/media/renderable/actor/Player.java, src/main/java/org/runejs/client/net/ISAAC.java, src/main/java/org/runejs/client/net/IncomingPackets.java, src/main/java/org/runejs/client/scene/tile/GenericTile.java
I removed a load of dummy arguments, generally these functions only had 1 call site so it was very easy to identify the dummys and remove them.
A couple of the methods had 2 or 3 call sites but it was easy enough to inspect them and figure out the logic.
--- client tested as working 😄
=> refactor: remove a load of dummys, mostly from `MovedStatics` class

src/main/java/org/runejs/client/Main.java, src/main/java/org/runejs/client/ProducingGraphicsBuffer_Sub1.java, src/main/java/org/runejs/client/io/Buffer.java, src/main/java/org/runejs/client/net/OutgoingPackets.java, src/main/java/org/runejs/client/net/PacketBuffer.java, src/main/java/org/runejs/client/net/VariableLengthPacketBuffer.java
Allows us to create a variable length packet where the length fits in a byte (type `-1`)
We can expand this in future if needed for variable length `-2` (length fits in a short), but I'm not sure if the client needs that functionality.
=> feat: create `VariableLengthPacketBuffer` to handle variable lengths

src/main/java/org/runejs/client/message/handler/rs435/RS435HandlerRegistry.java, src/main/java/org/runejs/client/message/handler/rs435/audio/PlayQuickSongMessageHandler.java, src/main/java/org/runejs/client/message/handler/rs435/audio/PlaySongMessageHandler.java, src/main/java/org/runejs/client/message/handler/rs435/audio/PlaySoundMessageHandler.java, src/main/java/org/runejs/client/message/inbound/audio/PlayQuickSongInboundMessage.java, src/main/java/org/runejs/client/message/inbound/audio/PlaySongInboundMessage.java, src/main/java/org/runejs/client/message/inbound/audio/PlaySoundInboundMessage.java, src/main/java/org/runejs/client/net/IncomingPackets.java, src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java, src/main/java/org/runejs/client/net/codec/runejs435/decoder/audio/PlayQuickSongMessageDecoder.java, src/main/java/org/runejs/client/net/codec/runejs435/decoder/audio/PlaySongMessageDecoder.java, src/main/java/org/runejs/client/net/codec/runejs435/decoder/audio/PlaySoundMessageDecoder.java
**note to reviewer: click on the first commit and then use the "next" button to review these commits one-by-one. They are in a logical order**
=> refactor: migrate audio-related packets to new packet system

src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java, src/main/java/org/runejs/client/message/outbound/interactions/NPCInteractionOutboundMessage.java, src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java, src/main/java/org/runejs/client/net/codec/runejs435/encoder/interactions/NPCInteractionMessageEncoder.java
**note to reviewer: click on the first commit and then use the "next" button to review these commits one-by-one. They are in a logical order**
Converts all NPC interaction packets into one message and encoder
=> refactor: convert NPC interaction packets to new system

src/main/java/org/runejs/client/Class33.java
the text colours of chat effects was broken, and the waves weren't working properly
will do another refactor of this area as there's a lot of quick wins around this chat code 
I think it came from some changes made in this PR https://github.com/runejs/refactored-client-435/pull/17/
=> fix: fix parameter order for chat effects

src/main/java/org/runejs/client/Class33.java, src/main/java/org/runejs/client/MovedStatics.java, src/main/java/org/runejs/client/media/renderable/actor/PlayerAppearance.java
- rename some arrays
- use constants instead of magic numbers (e.g. the `getNetworkCode()` for chat effects, and the `OVERHEAD_CHAT_COLORS` values)
-  this uses the enums from #96
- rename a varp
=> refactor: renaming around chat color/shape rendering, use new enums too

src/main/java/org/runejs/client/media/renderable/actor/Player.java, src/main/java/org/runejs/client/message/handler/rs435/RS435HandlerRegistry.java, src/main/java/org/runejs/client/message/handler/rs435/UpdatePlayersMessageHandler.java, src/main/java/org/runejs/client/message/inbound/updating/LocalPlayerMovementUpdate.java, src/main/java/org/runejs/client/message/inbound/updating/OtherPlayersMovementUpdate.java, src/main/java/org/runejs/client/message/inbound/updating/PlayerMovementUpdate.java, src/main/java/org/runejs/client/message/inbound/updating/RegisterNewPlayersUpdate.java, src/main/java/org/runejs/client/message/inbound/updating/UpdatePlayersInboundMessage.java, src/main/java/org/runejs/client/net/IncomingPackets.java, src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java, src/main/java/org/runejs/client/net/codec/runejs435/decoder/updating/UpdatePlayersMessageDecoder.java
Moves the player updating packet (`92`) into the new message pattern.
**Note to reviewer!!!** Click into the first commit, and use `Next` button to go through them in order. They are broken down into logical chunks, with notes in the extended commit message for each commit. I have also added notes saying where you can find the original reference for each function if you want to compare.
Tested:
- appearance
- equipment
- animations
- gfx
=> refactor: convert player updating packet to new message system

src/main/java/org/runejs/client/net/codec/runejs435/encoder/magic/CastMagicOnWidgetItemMessageEncoder.java
I missed this.. I've now checked, and there aren't any others like this
=> fix: reference buffer correctly in CastMagicOnWidgetItemMessageEncoder

src/main/java/org/runejs/client/scene/camera/SphericalCamera.java
The zoom velocity changes (#153) allowed the user to zoom past the max value, this fixes that issue
=> fix: clamp zoom between allowed values

src/main/java/org/runejs/client/media/Rasterizer3D.java, src/main/java/org/runejs/client/scene/SceneRenderer.java, src/main/java/org/runejs/client/scene/Util3d.java, src/main/java/org/runejs/client/scene/tile/GenericTile.java
We use `A`/`B`/`C`/`D` to talk about corners of tiles quite a bit, we should rename them to NE/NW/SE/SW.
=> refactor: document functions in Rasterizer3d, improve some naming

.github/workflows/build-and-publish.yml, .github/workflows/release-body.md
Adds a GitHub Actions workflow that attempts a gradle build upon receiving a git `tag` event. If the build succeeds, a release will be created.
It also does a build upon commits to master.
I have tested this in an independent repository, seen here: 
- https://github.com/charles-m-knox/actions-test
- https://github.com/charles-m-knox/actions-test/actions
- https://github.com/charles-m-knox/actions-test/releases
=> Add github actions workflow to build & release when tag events occur

src/main/java/org/runejs/client/ActionRowType.java, src/main/java/org/runejs/client/MovedStatics.java, src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java, src/main/java/org/runejs/client/language/English.java
Just like the title says - this adds a Teleport Here option, but only if the player is an admin and debug mode is enabled in the client config.
When clicked, the menu item sends a console command to the server (`move x y`).
=> Add "Teleport here" menu option when in debug mode and player is admin

config/client-435.conf.example.yaml, src/main/java/org/runejs/Configuration.java, src/main/java/org/runejs/client/Game.java, src/main/java/org/runejs/client/MovedStatics.java, src/main/java/org/runejs/client/frame/ScreenController.java, src/main/java/org/runejs/client/input/KeyFocusListener.java
Adds a configurable option to shift+click to drop. If `drop` is not available as a menu item, then holding shift will revert to the second highest priority item in the menu.
other minor changes:
- whitespace/minor formatting cleanup
- renamed one or two obvious tokens in the source code that probably came from deobfuscation
=> Add shift+click to drop

.vscode/settings.json
Adds a vscode IDE configuration option that tells the Java plugin to disable autoformat on save. This is to prevent massive diffs from future contributors working with vscode.
=> Add vscode workspace setting to ignore autoformatting in java files

gradle/wrapper/gradle-wrapper.properties, src/main/java/org/runejs/Configuration.java, src/main/java/org/runejs/client/Game.java, src/main/java/org/runejs/client/GameShell.java, src/main/java/org/runejs/client/LoginScreen.java, src/main/java/org/runejs/client/MovedStatics.java, src/main/java/org/runejs/client/frame/ScreenController.java, src/main/java/org/runejs/client/language/English.java, src/main/java/org/runejs/client/language/Native.java
=> Resizable loginscreen POC
