src/main/java/com/jagex/runescape/GameSocket.java
src/main/java/com/jagex/runescape/cache/media/SpotAnimDefinition.java
src/main/java/com/jagex/runescape/net/IncomingPackets.java
src/main/java/com/jagex/runescape/net/PacketType.java
src/main/java/com/jagex/runescape/scene/tile/FloorDecoration.java

Refactor the incoming packets so they can define their own sizes.
Not all the packets were refactored, but this is a good start

Refactor incoming packets

---

config/client-435.conf.example.yaml
src/main/java/org/runejs/Configuration.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/frame/console/Commands/ResizableCommand.java

Attempted a resizable fix, as on windows the client would not resize properly when going back to fixed mode. Additionally added a configuration for for the transparency on right click menus.

Resize fix

---

config/client-435.conf.example.yaml
src/main/java/org/runejs/Configuration.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/frame/console/Commands/ResizableCommand.java

Reverts runejs/refactored-client-435#79

Revert "Resize fix"

---

src/main/java/org/runejs/client/Class24.java
src/main/java/org/runejs/client/GameShell.java
src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/CacheArchive.java
src/main/java/org/runejs/client/cache/def/ActorDefinition.java
src/main/java/org/runejs/client/media/renderable/Item.java
src/main/java/org/runejs/client/media/renderable/actor/Npc.java
src/main/java/org/runejs/client/net/UpdateServer.java
src/main/java/org/runejs/client/net/UpdateServerNode.java
src/main/java/org/runejs/client/scene/InteractiveObject.java

Moved some static variables/methods and renamed some values associated with the Client Sided Js5 System.

Client sided Update Server code renaming / static moving

---

src/main/java/org/runejs/client/Class13.java
src/main/java/org/runejs/client/Class17.java
src/main/java/org/runejs/client/Class24.java
src/main/java/org/runejs/client/Class33.java
src/main/java/org/runejs/client/Class35.java
src/main/java/org/runejs/client/Class37.java
src/main/java/org/runejs/client/Class39.java
src/main/java/org/runejs/client/Class40_Sub3.java
src/main/java/org/runejs/client/Class51.java
src/main/java/org/runejs/client/Class55.java
src/main/java/org/runejs/client/ClientScriptRunner.java
src/main/java/org/runejs/client/Interface3.java
src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/CacheArchive.java
src/main/java/org/runejs/client/cache/def/GameObjectDefinition.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/frame/console/Console.java
src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/Rasterizer3D.java
src/main/java/org/runejs/client/media/renderable/actor/Player.java
src/main/java/org/runejs/client/net/ISAAC.java
src/main/java/org/runejs/client/scene/Scene.java

A lot of these only had 1 usage so I just used Intellij IDEA's "inline parameter" functionality. The others I just inspected the usages manually.

refactor: remove more dummy arguments

---

src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/message/InboundMessage.java
src/main/java/org/runejs/client/message/OutboundMessage.java
src/main/java/org/runejs/client/message/README.md
src/main/java/org/runejs/client/message/handler/MessageHandler.java
src/main/java/org/runejs/client/message/handler/MessageHandlerRegistry.java
src/main/java/org/runejs/client/message/handler/README.md
src/main/java/org/runejs/client/message/handler/rs435/RS435HandlerRegistry.java
src/main/java/org/runejs/client/net/IncomingPackets.java
src/main/java/org/runejs/client/net/OutgoingPackets.java
src/main/java/org/runejs/client/net/PacketBuffer.java
src/main/java/org/runejs/client/net/codec/MessageDecoder.java
src/main/java/org/runejs/client/net/codec/MessageEncoder.java
src/main/java/org/runejs/client/net/codec/MessagePacketCodec.java
src/main/java/org/runejs/client/net/codec/README.md
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java

This will allow future changes to support networking protocols for many different revisions in the same client. It will also allow us to more easily change our own networking structure in future to suit our needs.
This PR should be ready, but I'll be raising other PRs against this, to convert the packets themselves.

feat: create abstraction between packets and messages

---

src/main/java/org/runejs/client/ActionRowType.java
src/main/java/org/runejs/client/Class13.java
src/main/java/org/runejs/client/Class33.java
src/main/java/org/runejs/client/Class43.java
src/main/java/org/runejs/client/HuffmanEncoding.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterfaceArea.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/renderable/actor/Player.java

**note to reviewer: click on the first commit and then use the "next" button to review these commits one-by-one. They are in a logical order**
-----
- create `ActionRowType.CANCEL` for `1005`
- create `ActionRowType.CLOSE_WIDGET` for `9`
- create `ActionRowType.CLOSE_PERMANENT_CHATBOX_WIDGET` for `40`
Also moved `LOW_PRIORITY_MODIFIER` into a constant

refactor: a few refactors around `ActionRowType`

---

src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/message/outbound/interactions/PlayerInteractionOutboundMessage.java
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/interactions/PlayerInteractionMessageEncoder.java

**note to reviewer: click on the first commit and then use the "next" button to review these commits one-by-one. They are in a logical order**
Converts all player interaction packets into one message and encoder

refactor: convert player interaction packets to new system

---

src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java

I think it was from a bad merge

fix: fix bad imports in packet codec

---

src/main/java/org/runejs/client/message/handler/rs435/RS435HandlerRegistry.java
src/main/java/org/runejs/client/message/handler/rs435/misc/LogoutMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/misc/UpdateCarryWeightMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/misc/UpdateRunEnergyMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/misc/UpdateSkillMessageHandler.java
src/main/java/org/runejs/client/message/inbound/misc/LogoutMessage.java
src/main/java/org/runejs/client/message/inbound/misc/UpdateCarryWeightMessage.java
src/main/java/org/runejs/client/message/inbound/misc/UpdateRunEnergyMessage.java
src/main/java/org/runejs/client/message/inbound/misc/UpdateSkillMessage.java
src/main/java/org/runejs/client/net/IncomingPackets.java
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/misc/LogoutMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/misc/UpdateCarryWeightMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/misc/UpdateRunEnergyMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/misc/UpdateSkillMessageDecoder.java

Converts the following packets:
- logout
- update run energy
- update carried weight
- update skill
Recommend to go commit-by-commit, the work is broken down nicely.

refactor: convert logout and stat update packets to new message format

---

src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/input/KeyFocusListener.java

This was broken in https://github.com/runejs/refactored-client-435/commit/fdbc3fd0a30c18c9cb78ccc1ef77dc93567ed233 and caused an error when trying to render a walkable interface

fix: fix walkable interface rendering

---

src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/message/outbound/chat/SetChatOptionsOutboundMessage.java
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/chat/SetChatOptionsMessageEncoder.java

There is an [open server issue](https://github.com/runejs/server/issues/400) relating to chat/chat options.
This PR is tested and works well in all scenarios except the one described in that issue.

refactor: convert "set chat options" packet to message

---

src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/media/renderable/actor/PlayerAppearance.java
src/main/java/org/runejs/client/message/outbound/widget/CloseWidgetsOutboundMessage.java
src/main/java/org/runejs/client/message/outbound/widget/container/DragWidgetItemOutboundMessage.java
src/main/java/org/runejs/client/message/outbound/widget/container/DropWidgetItemOutboundMessage.java
src/main/java/org/runejs/client/message/outbound/widget/input/ClickPleaseWaitWidgetOutboundMessage.java
src/main/java/org/runejs/client/message/outbound/widget/input/ClickWidgetButtonOutboundMessage.java
src/main/java/org/runejs/client/message/outbound/widget/input/SubmitAppearanceOutboundMessage.java
src/main/java/org/runejs/client/net/PacketBuffer.java
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/CloseWidgetsMessageEncoder.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/container/DragWidgetItemMessageEncoder.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/container/DropWidgetItemMessageEncoder.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/input/ClickPleaseWaitWidgetMessageEncoder.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/input/ClickWidgetButtonMessageEncoder.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/widget/input/SubmitAppearanceMessageEncoder.java

- submit appearance
- drag widget item
- drop widget item
- please wait.. clicks
- close widget
- click widget button

refactor: convert remaining outbound widget messages

---

src/main/java/org/runejs/client/message/handler/rs435/RS435HandlerRegistry.java
src/main/java/org/runejs/client/message/handler/rs435/world/item/AddGroundItemMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/world/item/RemoveGroundItemMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/world/item/UpdateGroundItemAmountMessageHandler.java
src/main/java/org/runejs/client/message/inbound/world/item/AddGroundItemInboundMessage.java
src/main/java/org/runejs/client/message/inbound/world/item/RemoveGroundItemInboundMessage.java
src/main/java/org/runejs/client/message/inbound/world/item/UpdateGroundItemAmountInboundMessage.java
src/main/java/org/runejs/client/net/IncomingPackets.java
src/main/java/org/runejs/client/net/codec/runejs435/RuneJS435PacketCodec.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/world/item/AddGroundItemExcludePlayerMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/world/item/AddGroundItemMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/world/item/RemoveGroundItemMessageDecoder.java
src/main/java/org/runejs/client/net/codec/runejs435/decoder/world/item/UpdateGroundItemAmountMessageDecoder.java

I've kept the related code in `parseMapIncomingPacket` for the time being, so I don't forget which packets are associated with the bulk update packet.

refactor: convert ground item packets to messages

---

src/main/java/org/runejs/client/Class24.java
src/main/java/org/runejs/client/Class40_Sub5_Sub15.java
src/main/java/org/runejs/client/Class57.java
src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/cache/media/AnimationSequence.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/media/renderable/actor/Pathfinding.java
src/main/java/org/runejs/client/message/outbound/WalkOutboundMessage.java
src/main/java/org/runejs/client/scene/tile/Wall.java

- member and argument renaming
- reorder parameters
- move statics to Pathfinding class
- use `0b` binary notation for bitmasks

refactor: refactor Pathfinding.doWalkTo method

---

src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/media/renderable/actor/Pathfinding.java
src/main/java/org/runejs/client/message/outbound/WalkOutboundMessage.java
src/main/java/org/runejs/client/net/codec/runejs435/encoder/WalkMessageEncoder.java

This fixes the issue where minimap walking results in packets getting out of sync, introduced in #145

fix: send minimap analytic data correctly

---

src/main/java/org/runejs/client/Class12.java
src/main/java/org/runejs/client/Class26.java
src/main/java/org/runejs/client/Class37.java
src/main/java/org/runejs/client/Class49.java
src/main/java/org/runejs/client/Class60.java
src/main/java/org/runejs/client/Class65.java
src/main/java/org/runejs/client/GameShell.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/ProducingGraphicsBuffer_Sub1.java
src/main/java/org/runejs/client/Projectile.java
src/main/java/org/runejs/client/frame/Minimap.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/renderable/Item.java
src/main/java/org/runejs/client/message/handler/rs435/camera/CutsceneCameraLookToMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/camera/CutsceneCameraMoveToMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/camera/CutsceneExitMessageHandler.java
src/main/java/org/runejs/client/message/handler/rs435/camera/ShakeCameraMessageHandler.java
src/main/java/org/runejs/client/scene/GroundItemTile.java
src/main/java/org/runejs/client/scene/SceneCamera.java
src/main/java/org/runejs/client/scene/SceneCluster.java
src/main/java/org/runejs/client/scene/tile/SceneTile.java
src/main/java/org/runejs/client/scene/tile/Wall.java

Moving things into one place temporarily so we can get a better view and refactor more easily.

refactor: create SceneCamera class, move statics to it

---

src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/renderable/Item.java
src/main/java/org/runejs/client/scene/SceneCamera.java

feat: use velocity for smoother zooming

---

src/main/java/org/runejs/Configuration.java
src/main/java/org/runejs/client/Class60.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/sound/MusicSystem.java

Fix a refactoring typo, and save client config to disk if it does not exist

---

src/main/java/org/runejs/client/Class13.java
src/main/java/org/runejs/client/Class40_Sub5_Sub15.java
src/main/java/org/runejs/client/Class44.java
src/main/java/org/runejs/client/Projectile.java
src/main/java/org/runejs/client/cache/def/ItemDefinition.java
src/main/java/org/runejs/client/media/renderable/actor/Actor.java
src/main/java/org/runejs/client/media/renderable/actor/Npc.java
src/main/java/org/runejs/client/media/renderable/actor/Player.java
src/main/java/org/runejs/client/media/renderable/actor/PlayerAppearance.java
src/main/java/org/runejs/client/message/handler/rs435/updating/UpdateNPCsMessageHandler.java

Still quite a bit of work to do in this area

refactor: partial renaming of actor updating

---

src/main/java/org/runejs/client/Class33.java
src/main/java/org/runejs/client/Class35.java
src/main/java/org/runejs/client/Class37.java
src/main/java/org/runejs/client/Class44.java
src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/ProducingGraphicsBuffer.java
src/main/java/org/runejs/client/cache/def/ActorDefinition.java
src/main/java/org/runejs/client/frame/Minimap.java
src/main/java/org/runejs/client/message/handler/rs435/misc/SetHintIconMessageHandler.java
src/main/java/org/runejs/client/net/ISAAC.java
src/main/java/org/runejs/client/scene/Point2d.java
src/main/java/org/runejs/client/scene/tile/FloorDecoration.java

There were two static variables which were used to hold the most recently calculated "projection" - this only made it more difficult to work with

refactor: remove static screen projection, use pure function to calculate instead

---

src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/SpotAnim.java
src/main/java/org/runejs/client/frame/DebugTools.java
src/main/java/org/runejs/client/frame/console/Commands/DebugWalkCommand.java
src/main/java/org/runejs/client/frame/console/Console.java
src/main/java/org/runejs/client/media/renderable/actor/Pathfinding.java

feat: create `walkpath` debug command

---

src/main/java/org/runejs/client/Main.java
src/main/java/org/runejs/client/frame/DebugTools.java
src/main/java/org/runejs/client/frame/console/Commands/DebugClippingCommand.java
src/main/java/org/runejs/client/frame/console/Console.java
src/main/java/org/runejs/client/scene/util/CollisionMap.java

feat: create debugclip view to inspect clipping info

---

src/main/java/org/runejs/client/Class17.java
src/main/java/org/runejs/client/Class33.java
src/main/java/org/runejs/client/Class37.java
src/main/java/org/runejs/client/Class49.java
src/main/java/org/runejs/client/Game.java
src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/LinkedList.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/frame/ScreenController.java
src/main/java/org/runejs/client/input/KeyFocusListener.java
src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/renderable/actor/Npc.java
src/main/java/org/runejs/client/net/OutgoingPackets.java
src/main/java/org/runejs/client/scene/SceneCluster.java

also moves some mouse/keyboard stuff

refactor: move packetBuffer to OutgoingPackets

---

src/main/java/org/runejs/client/Landscape.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/frame/Minimap.java
src/main/java/org/runejs/client/message/handler/rs435/world/object/RotateAnimateObjectMessageHandler.java
src/main/java/org/runejs/client/scene/Scene.java
src/main/java/org/runejs/client/scene/SceneCluster.java
src/main/java/org/runejs/client/scene/tile/SceneTile.java
src/main/java/org/runejs/client/scene/util/CollisionMap.java

ty @thedaneeffect for some of these values, especially the wall culling arrays

refactor: rename contents of Scene class

---

src/main/java/org/runejs/client/cache/bzip/BZip.java
src/main/java/org/runejs/client/cache/bzip/BZipContext.java

This file needs some more work

refactor: renaming for Bzip2

---

src/main/java/org/runejs/client/Game.java
src/main/java/org/runejs/client/GameShell.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java
src/main/java/org/runejs/client/input/KeyFocusListener.java
src/main/java/org/runejs/client/input/MouseHandler.java
src/main/java/org/runejs/client/media/Rasterizer3D.java
src/main/java/org/runejs/client/media/renderable/Model.java
src/main/java/org/runejs/client/media/renderable/Renderable.java
src/main/java/org/runejs/client/media/renderable/actor/Actor.java
src/main/java/org/runejs/client/media/renderable/actor/Npc.java
src/main/java/org/runejs/client/media/renderable/actor/PlayerAppearance.java
src/main/java/org/runejs/client/scene/SceneCluster.java
src/main/java/org/runejs/client/util/Signlink.java

All statics now either live in an "appropriate" place, or in `MovedStatics`.
The only exceptions are in the `Scene` class which I'm going to tackle separately with a clear view

refactor: move almost all remaining statics

---

src/main/java/org/runejs/client/Game.java
src/main/java/org/runejs/client/MovedStatics.java
src/main/java/org/runejs/client/cache/media/ImageRGB.java
src/main/java/org/runejs/client/frame/Minimap.java

Preparation for moving Fixed frame to FrameRenderer pattern

refactor: refactoring around minimap/frame drawing

---

src/main/java/org/runejs/client/cache/media/gameInterface/GameInterface.java

broken in afbeafc5506818a1b019147d381483cee1b9e0f6 (#96)

fix: send private message text correctly
